# Generated by Django 5.0.6 on 2026-03-14 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('local_service', 'Local Service'), ('pharmacy', 'Pharmacy'), ('agro_store', 'Agro Store')], max_length=30)),
                ('service_type', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('mechanic', 'Mechanic'), ('tractor_rental', 'Tractor Rental'), ('pump_repair', 'Pump Repair'), ('medicines', 'Medicines'), ('fertilizers', 'Fertilizers'), ('seeds', 'Seeds'), ('pesticides', 'Pesticides'), ('tools', 'Tools')], max_length=40)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('max_service_km', models.FloatField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profiles', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=200)),
                ('eta', models.CharField(blank=True, max_length=80)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('delivery_time', models.CharField(blank=True, max_length=80)),
                ('delivery_option', models.CharField(blank=True, max_length=80)),
                ('distance_km', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.providerprofile')),
            ],
            options={
                'ordering': ['price', 'distance_km', '-provider__rating'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('service', 'Service'), ('medicine', 'Medicine'), ('farm', 'Farm')], max_length=20)),
                ('service_type', models.CharField(blank=True, max_length=40)),
                ('product_name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('prescription_image', models.URLField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_request', to='core.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.request'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='core.providerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='core.appuser')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.request')),
            ],
            options={
                'unique_together': {('request', 'user', 'provider')},
            },
        ),
    ]
