# Generated by Django 5.2.12 on 2026-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="pin",
            field=models.CharField(default="123456", max_length=6),
        ),
    ]
